<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_GradeThree</name>
   <tag></tag>
   <elementGuidId>badd3c7b-0804-4704-9022-0bc8c4dca14a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='msform']/fieldset[5]/div/div/div[11]/div[3]/div[2]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='msform']/fieldset[5]/div/div/div[11]/div[3]/div[2]/div/select</value>
   </webElementProperties>
</WebElementEntity>
