<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Message</name>
   <tag></tag>
   <elementGuidId>ba4055e1-0aa5-454d-80e9-a2024f657398</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[1]/div[2]/div/div/div/div[2]/div[4]/div/div/form/div[2]/div/div/div/div/div[3]/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[1]/div[2]/div/div/div/div[2]/div[4]/div/div/form/div[2]/div/div/div/div/div[3]/div/textarea</value>
   </webElementProperties>
</WebElementEntity>
