<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gender</name>
   <tag></tag>
   <elementGuidId>984fc7dd-9dd6-4371-9092-dcd16886296e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='msform']/fieldset[1]/div/div/div/div[8]/div/label[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='msform']/fieldset[1]/div/div/div/div[8]/div/label[1]/input</value>
   </webElementProperties>
</WebElementEntity>
