<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date</name>
   <tag></tag>
   <elementGuidId>2ee68c13-96b6-40a3-abb1-1df088d1a545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[2]/div/div/div[3]/div[1]/table/tbody/tr[3]/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[2]/div/div/div[3]/div[1]/table/tbody/tr[3]/td[3]/a</value>
   </webElementProperties>
</WebElementEntity>
