<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_UniversityCourseOther</name>
   <tag></tag>
   <elementGuidId>79c002b5-819d-4b51-a0f5-2a4b71611062</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='msform']/fieldset[2]/div/div/div[3]/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='msform']/fieldset[2]/div/div/div[3]/div[2]/div/input</value>
   </webElementProperties>
</WebElementEntity>
