<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_IBP1</name>
   <tag></tag>
   <elementGuidId>d6d98f4e-bbda-45ef-a273-c37be5e7e979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='msform']/fieldset[5]/div/div/div[12]/div[1]/div[1]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='msform']/fieldset[5]/div/div/div[12]/div[1]/div[1]/select</value>
   </webElementProperties>
</WebElementEntity>
