<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_HEYear</name>
   <tag></tag>
   <elementGuidId>2e3a99cc-6433-4e71-83e3-533802bd0740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>././/*[@id='msform']/fieldset[5]/div/div/div[12]/div/div[3]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>././/*[@id='msform']/fieldset[5]/div/div/div[12]/div/div[3]/div/select</value>
   </webElementProperties>
</WebElementEntity>
