<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>25000</name>
   <tag></tag>
   <elementGuidId>54da36e9-1f9f-40b6-bd04-5307995afd0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='msform']/fieldset[6]/div/div/div/div[1]/div[2]/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='msform']/fieldset[6]/div/div/div/div[1]/div[2]/label/input</value>
   </webElementProperties>
</WebElementEntity>
