<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ehnicity5</name>
   <tag></tag>
   <elementGuidId>f695d9b0-557b-4107-9628-70d77b1fcc1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[1]/div/div[2]/div/div/form/fieldset[7]/div/div/div[2]/div[1]/div/select/optgroup[1]/option[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[1]/div/div[2]/div/div/form/fieldset[7]/div/div/div[2]/div[1]/div/select/optgroup[1]/option[5]</value>
   </webElementProperties>
</WebElementEntity>
