<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Name</name>
   <tag></tag>
   <elementGuidId>46fd2c11-0417-4ceb-a301-b038bb6f7bba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[1]/div[2]/div/div/div/div[2]/div[4]/div/div/form/div[2]/div/div/div/div/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[1]/div[2]/div/div/div/div[2]/div[4]/div/div/form/div[2]/div/div/div/div/div[1]/div/input</value>
   </webElementProperties>
</WebElementEntity>
