<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>University</name>
   <tag></tag>
   <elementGuidId>fb24c96a-da1d-4e0d-934d-b889692909fd</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>university_id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>form_data.university_id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>x.id as x.short_name for x in universities</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>checkOtherUniversity(form_data.university_id)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AberdeenAbertayAberystwythAnglia RuskinArdenArts University BournemouthAstonBangorBathBath SpaBedfordshireBirkbeckBirminghamBirmingham CityBishop GrossetesteBoltonBournemouthBPPBradfordBrightonBristolBrunelBuckinghamBuckinghamshire NewCambridgeCanterbury Christ ChurchCardiffCardiff MetropolitanCentral LancashireChesterChichesterCityCourtauld Institute of ArtCoventryCranfieldCreative ArtsCumbriaDe MontfortDerbyDundeeDurhamEast AngliaEast LondonEdge HillEdinburghEdinburgh Napier EssexExeterFalmouthGlasgowGlasgow CaledonianGloucestershireGlyndwrGoldsmithsGreenwichHarper AdamsHeriot-WattHertfordshireHeythrop CollegeHighlands &amp; IslandsHuddersfieldHullifs School of FinanceImperialInstitute of EducationKaplan Law SchoolKeeleKentKing'sKingstonLancasterLeedsLeeds BeckettLeeds TrinityLeicesterLincolnLiverpoolLiverpool HopeLiverpool John MooresLondon Business SchoolLondon MetropolitanLondon School of Hygiene and Tropical MedicineLondon South BankLoughboroughLSEManchesterManchester MetropolitanMiddlesexNew college of humanitiesNewcastleNewman University CollegeNorthamptonNorthumbriaNorwich University of the ArtsNottinghamNottingham TrentOpen UniversityOtherOxfordOxford BrookesPlymouthPlymouth MarJohnPortsmouthQueen MargaretQueen MaryQueen'sReadingRegent'sRobert GordonRoehamptonRoyal Academy of MusicRoyal Agricultural UniversityRoyal Central School of Speech and DramaRoyal College of ArtRoyal College of MusicRoyal HollowayRoyal Veterinary CollegeSalfordSheffieldSheffield HallamSOASSouth WalesSouthamptonSouthampton SolentSt Andrew'sSt George'sSt Mary'sStaffordshireStirlingStrathclydeSuffolkSunderlandSurreySussexSwanseaTeessideTrinity Saint David (UoW)UCLUlsterUniversity College BirminghamUniversity of LawUniversity of London InstitutesUniversity of the Arts LondonUniversity of the West of EnglandUniversity of the West of ScotlandUniversity of West LondonWarwickWestminsterWinchesterWolverhamptonWorcesterYorkYork St John</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;university_id&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='university_id']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='tab2']/div[2]/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='University'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='University Course'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='University Course Category'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
