<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email</name>
   <tag></tag>
   <elementGuidId>bdf12fa8-815b-4273-b4e0-ec6b4ced4bca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='coordinatorModal']/div/div/form/div[2]/div/div/div/div/div[2]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='coordinatorModal']/div/div/form/div[2]/div/div/div/div/div[2]/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
