<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Problemsolving_One</name>
   <tag></tag>
   <elementGuidId>c4438a60-18fd-4200-a763-ddf2a3128269</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>answer.answer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I can integrate information and data, making their meaning and implication clear to the audience.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6&quot;)/div[@class=&quot;question-wrapper ng-scope&quot;]/div[@class=&quot;panel panel-info text-left&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-md-12 list-timeline ng-scope&quot;]/div[@class=&quot;col-md-12 list-timeline-section bg-light col-md-15-neg&quot;]/div[@class=&quot;col-md-12 list-timeline-detail&quot;]/div[@class=&quot;form-group form-animate-checkbox&quot;]/table[1]/tbody[1]/tr[1]/td[2]/label[1]/span[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='6']/div[2]/div/div[2]/div/div[3]/div/div/div/table/tbody/tr/td[2]/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I can confidently draw appropriate conclusions from a large amount of information and evidence.'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None of these'])[8]/preceding::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[6]/div[2]/div/div[2]/div/div[3]/div/div/div/table/tbody/tr/td[2]/label/span</value>
   </webElementXpaths>
</WebElementEntity>
