<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Current</name>
   <tag></tag>
   <elementGuidId>04e853fb-2ec0-45c2-a316-51c61a5af202</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='msform']/fieldset/div[2]/div[16]/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='msform']/fieldset/div[2]/div[16]/div/select</value>
   </webElementProperties>
</WebElementEntity>
