<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>careerpage</name>
   <tag></tag>
   <elementGuidId>ef96438f-0def-40a7-b961-3e31abe2a2ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='msform']/fieldset[4]/div[1]/div/div/table/tbody/tr[2]/td/label/table/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='msform']/fieldset[4]/div[1]/div/div/table/tbody/tr[2]/td/label/table/tbody/tr/td[2]</value>
   </webElementProperties>
</WebElementEntity>
