<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>stronginterest</name>
   <tag></tag>
   <elementGuidId>b4e5c853-5711-40cc-8593-3440c12c149b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='msform']/fieldset[4]/div[2]/div/div/table/tbody/tr[1]/td[2]/div/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='msform']/fieldset[4]/div[2]/div/div/table/tbody/tr[1]/td[2]/div/label/input</value>
   </webElementProperties>
</WebElementEntity>
