<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Volunteer</name>
   <tag></tag>
   <elementGuidId>7c0ac1a6-efca-46b8-83f1-862e3a2858bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/header/nav/div/div[2]/ul/li[3]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/header/nav/div/div[2]/ul/li[3]/ul/li[3]/a</value>
   </webElementProperties>
</WebElementEntity>
